### PR TITLE
Enhancement/8 unify exceptions handling

### LINKED ISSUE #8: Unify exceptions handling
## Problem

We need to add our new exception builder to the project and unify the exceptions handling

### PR DESCRIPTION
**Pull request by chiaradiamarcelo**
Closes #8.

### CODE REVIEW

File: src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java [hunk 1]
```diff
@@ -87,8 +88,8 @@ private String buildColumnProjectionString(final SqlColumn column, final String
             }
             return false;
         } catch (final AdapterException exception) {
-            throw new SqlGenerationVisitorException("Exception during deserialization of ColumnAdapterNotes. ",
-                    exception);
+            throw new SqlGenerationVisitorException(ExaError.messageBuilder("E-PGVS-7")
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java:91]: Maybe this is a Fatal, not an error? I think also "Create a GitHub issue" mitigation fits here

File: src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java [hunk 2]
```diff
@@ -283,8 +284,9 @@ public String visit(final SqlFunctionAggregateGroupConcat function) throws Adapt
             builder.append(") ");
             return builder.toString();
         } else {
-            throw new SqlGenerationVisitorException(
-                    "List of arguments of SqlFunctionAggregateGroupConcat should have one argument.");
+            throw new SqlGenerationVisitorException(ExaError.messageBuilder("E-PGVS-8")
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java:287]: I would remove the check for arguments number here because I prefer to check it on the parsing level

**Review by AnastasiiaSergienko — CHANGES_REQUESTED** [review]

File: src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java (hunk 2 above)
Comment (AnastasiiaSergienko) [reply src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java:287]: If you don't wan't to remove it, then maybe it's also fatal with mitigation as the previous one

File: src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java (hunk 1 above)
Comment (chiaradiamarcelo) [reply src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java:91]: As this is going to be fixed in the Parser directly, and this we'll be removed, for now I'll leave it as it is

File: src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java (hunk 2 above)
Comment (chiaradiamarcelo) [reply src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java:287]: Removed the validation and creating a ticket for doing it in vs-common-java

**Review by AnastasiiaSergienko — APPROVED** [review]
